INSERT INTO PERMISSAO (ID, PERMISSAO, DESCRICAO)
VALUES (1, 'ADMIN', 'Administrador');
INSERT INTO PERMISSAO (ID, PERMISSAO, DESCRICAO)
VALUES (2, 'PROPRIETARIO', 'Proprietário');
INSERT INTO PERMISSAO (ID, PERMISSAO, DESCRICAO)
VALUES (3, 'SOCIO', 'Sócio');
INSERT INTO PERMISSAO (ID, PERMISSAO, DESCRICAO)
VALUES (4, 'GERENTE', 'Gerente');
INSERT INTO PERMISSAO (ID, PERMISSAO, DESCRICAO)
VALUES (5, 'FUNCIONARIO', 'Funcionário');

INSERT INTO USUARIO (ID, CPF, DATA_CADASTRO, DATA_NASCIMENTO, EMAIL, NOME, SENHA, SEXO, SITUACAO)
VALUES (1, '103.324.589-54', NOW(), '1998-03-31', 'victorhugonegrisoli.ccs@gmail.com', 'Victor Hugo Negrisoli', '$2a$10$uOy6Cs2KXHXR.ZO0KyGh1eupbj1q40vWss2Al2m8tM/R5ZCQZv4p6', 'MASCULINO', 'ATIVO');

INSERT INTO USUARIO_PERMISSAO (FK_USUARIO, FK_PERMISSAO) VALUES (1, 1);